// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znlmsmbtjnxtrenlrlkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpubG1zbWJ0am54dHJlbmxybGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQwOTIsImV4cCI6MjA2NTQ3MDA5Mn0.mqeqIQcgdMF3q-Cm3JsTezrVCHEfm8Q9b_tCzVp1OOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);